# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Lint

on:
  workflow_call:
    
permissions:
  contents: read
  
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      checks: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: task generate
      - run: mkdir -p bin
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
          
  super-linter:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write # To report GitHub Actions status checks

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: super-linter/super-linter/slim@v6.8.0  # x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # To report GitHub Actions status checks
          VALIDATE_GO: false
          VALIDATE_GO_MODULES: false
          VALIDATE_JSCPD: false
          FILTER_REGEX_EXCLUDE: '.*/docs/.*\.md$'